ArrayList<> data = [ {
  "name": "Sakura Market Bag",
  "difficulty": 3,
  "imageURL": "/home/lizzie/Desktop/nology/solo-project/crochet-town-backend/src/main/src/main/java/org/crochetData/images/79943115-591c-495c-86f1-fbc6d4316b74.jpg_0_-_1000x1000.png",
  "category": "Clothing",
  "rating": 0.0,
  "favourites_count": 5,
  "reviews": 0,
  "authorID" : 1,
  "hook_size": 4.0,
  "end_size": 32,
  "colours": ["lime green"],
  "pattern": {}},
 {
  "name": "Mini Whale",
  "difficulty": 1,
  "imageURL": "/home/lizzie/Desktop/nology/solo-project/crochet-town-backend/src/main/src/main/java/org/crochetData/images/27a43459-c60c-44a2-b706-8933ac02ecce.jpg_0_-_416x416.png",
  "category": "Toys",
  "rating": 0.0,
  "favourites_count": 0,
  "reviews": 0,
  "authorID" : 2,
  "hook_size": 3.5,
  "end_size": 10,
  "colours": ["blue", "white"],
  "pattern": {}},
  {
  "name": "Lemon Granny Square",
  "difficulty": 7,
  "imageURL": "/home/lizzie/Desktop/nology/solo-project/crochet-town-backend/src/main/src/main/java/org/crochetData/images/27a43459-c60c-44a2-b706-8933ac02ecce.jpg_0_-_416x416.png",
  "category": "Granny Square",
  "rating": 0.0,
  "favourites_count": 0,
  "reviews": 0,
  "authorID" : 2,
  "hook_size": 4.0,
  "end_size": 13,
  "colours": ["yellow", "lemon", "pistachio", "dark green"],
  "pattern":  {}},
{
  "name": "Stitch Plush Toy",
  "difficulty": 2,
  "imageURL": "/home/lizzie/Desktop/nology/solo-project/crochet-town-backend/src/main/src/main/java/org/crochetData/images/a82ae4d1-53d5-4ed1-b671-982e0076b427.jpg_0_-_1000x1000.png",
  "category": "Plush Toy",
  "rating": 0.0,
  "favourites_count": 0,
  "reviews": 0,
  "authorID" : 2,
  "hook_size": 4.0,
  "end_size": 44,
  "colours": ["blue", "green"],
  "pattern": {}},




 {
  "name": "Baby Blanket",
  "difficulty": "3",
  "imageURL": "/home/lizzie/Desktop/nology/solo-project/crochet-town-backend/src/main/src/main/java/org/crochetData/images/a82ae4d1-53d5-4ed1-b671-982e0076b427.jpg_0_-_1000x1000.png",
  "category": "Baby",
  "rating": 0.0,
  "favourites_count": 0,
  "reviews": 0,
  "authorID" : 4,
  "hook_size": 6.5,
  "end_size": 35,
  "colours": ["baby pink"],
  "pattern": {}}

]